site_name: wolfSSL Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: Copyright Â© 2023 wolfSSL Inc.
nav:
    - "1. Introduction": index.md
    - "2. Building wolfSSL": chapter02.md
    - "3. Getting Started": chapter03.md
    - "4. Features": chapter04.md
    - "5. Portability": chapter05.md
    - "6. Callbacks": chapter06.md
    - "7. Keys and Certificates": chapter07.md
    - "8. Debugging": chapter08.md
    - "9. Library Design": chapter09.md
    - "10. wolfCrypt Usage Reference": chapter10.md
    - "11. SSL Tutorial": chapter11.md
    - "12. Best Practices for Embedded Devices": chapter12.md
    - "13. OpenSSL Compatibility": chapter13.md
    - "14. Licensing": chapter14.md
    - "15. Support and Consulting": chapter15.md
    - "16. wolfSSL Updates": chapter16.md
    - "A. wolfSSL API Reference":
      - "CertManager API": group__CertManager.md
      - "Memory Handling": group__Memory.md
      - "OpenSSL API": group__openSSL.md
      - "wolfSSL Certificates and Keys": group__CertsKeys.md
      - "wolfSSL Connection, Session, and I/O": group__IO.md
      - "wolfSSL Context and Session Set Up": group__Setup.md
      - "wolfSSL Error Handling and Reporting": group__Debug.md
      - "wolfSSL Initialization/Shutdown": group__TLS.md
    - "B. wolfCrypt API Reference":
      - "ASN.1": group__ASN.md
      - "Base Encoding": group__Base__Encoding.md
      - "Compression": group__Compression.md
      - "Error Reporting": group__Error.md
      - "IoT-Safe Module": group__IoTSafe.md
      - "Key and Cert Conversion": group__Keys.md
      - "Logging": group__Logging.md
      - "Math API": group__Math.md
      - "Random Number Generation": group__Random.md
      - "Signature API": group__Signature.md
      - "wolfCrypt Init and Cleanup": group__wolfCrypt.md
      - "Algorithms - 3DES": group__DES.md
      - "Algorithms - AES": group__AES.md
      - "Algorithms - ARC4": group__ARC4.md
      - "Algorithms - BLAKE2": group__BLAKE2.md
      - "Algorithms - Camellia": group__Camellia.md
      - "Algorithms - ChaCha": group__ChaCha.md
      - "Algorithms - ChaCha20_Poly1305": group__ChaCha20Poly1305.md
      - "Algorithms - CMAC ": group__CMAC.md
      - "Callbacks - CryptoCb": group__Crypto.md
      - "Algorithms - Curve25519": group__Curve25519.md
      - "Algorithms - Curve448": group__Curve448.md
      - "Algorithms - DSA": group__DSA.md
      - "Algorithms - Diffie-Hellman": group__Diffie-Hellman.md
      - "Algorithms - ECC": group__ECC.md
      - "Algorithms - ED25519": group__ED25519.md
      - "Algorithms - ED448": group__ED448.md
      - "ECCSI API Reference":
        - "Overview of ECCSI": group__ECCSI__Overview.md
        - "Setup ECCSI Key": group__ECCSI__Setup.md
        - "Operations for Signing and Verifying with ECCSI Key": group__ECCSI__Operations.md
      - "SAKKE API Reference":
        - "Overview of SAKKE Key": group__SAKKE__Overview.md
        - "Setup SAKKE Key": group__SAKKE__Setup.md
        - "Operations on/with SAKKE RSK": group__SAKKE__RSK.md
        - "Operations using SAKKE Key": group__SAKKE__Operations.md
      - "Algorithms - HMAC": group__HMAC.md
      - "Algorithms - MD2": group__MD2.md
      - "Algorithms - MD4": group__MD4.md
      - "Algorithms - MD5": group__MD5.md
      - "Algorithms - Password Based": group__Password.md
      - "Algorithms - PKCS7": group__PKCS7.md
      - "Algorithms - PKCS11": group__PKCS11.md
      - "Algorithms - Poly1305": group__Poly1305.md
      - "Algorithms - PSA": group__PSA.md
      - "Algorithms - RIPEMD": group__RIPEMD.md
      - "Algorithms - RSA": group__RSA.md
      - "Algorithms - SHA 128/224/256/384/512": group__SHA.md
      - "Algorithms - SipHash": group__SipHash.md
      - "Algorithms - SRP": group__SRP.md
    - "C. API Header Files":
      - aes_8h.md
      - arc4_8h.md
      - asn_8h.md
      - asn__public_8h.md
      - blake2_8h.md
      - bn_8h.md
      - camellia_8h.md
      - chacha20__poly1305_8h.md
      - chacha_8h.md
      - cmac_8h.md
      - coding_8h.md
      - compress_8h.md
      - cryptocb_8h.md
      - curve25519_8h.md
      - curve448_8h.md
      - des3_8h.md
      - dh_8h.md
      - doxygen__groups_8h.md
      - doxygen__pages_8h.md
      - dsa_8h.md
      - ecc_8h.md
      - eccsi_8h.md
      - ed25519_8h.md
      - ed448_8h.md
      - error-crypt_8h.md
      - evp_8h.md
      - hash_8h.md
      - hmac_8h.md
      - iotsafe_8h.md
      - logging_8h.md
      - md2_8h.md
      - md4_8h.md
      - md5_8h.md
      - memory_8h.md
      - pem_8h.md
      - pkcs11_8h.md
      - pkcs7_8h.md
      - poly1305_8h.md
      - psa_8h.md
      - pwdbased_8h.md
      - quic_8h.md
      - random_8h.md
      - ripemd_8h.md
      - rsa_8h.md
      - sakke_8h.md
      - sha256_8h.md
      - sha512_8h.md
      - sha_8h.md
      - signature_8h.md
      - siphash_8h.md
      - srp_8h.md
      - ssl_8h.md
      - tfm_8h.md
      - types_8h.md
      - wc__encrypt_8h.md
      - wc__port_8h.md
      - wolfio_8h.md
    - "D. SSL/TLS Overview": appendix04.md
    - "E. RFCs, Specifications, and Reference": appendix05.md
    - "F. Error Codes": appendix06.md
    - "G. Experimenting with Post-Quantum Cryptography": appendix07.md
    - "H. wolfSSL Porting Guide": appendix08.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
extra:
    generator: false
use_directory_urls: false
