site_name: Bouncy Castle Migration Guide
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: Copyright Â© 2026 wolfSSL Inc.
nav:
    - "1. Introduction": index.md
    - "2. Overview of Differences": chapter02.md
    - "3. JCE Provider Migration": chapter03.md
    - "4. JSSE Provider Migration": chapter04.md
    - "5. BC Proprietary API Migration": chapter05.md
    - "6. FIPS 140-3 Considerations": chapter06.md
    - "7. Troubleshooting": chapter07.md
    - "8. Support": chapter08.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
extra:
    generator: false
use_directory_urls: false
