site_name: wolfSentry Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: Copyright Â© 2022 wolfSSL Inc.
nav:
    - "1. Introduction": index.md
    - "2. Building wolfSentry": chapter02.md
    - "3. wolfSentry API": chapter03.md
    - "4. wolfSentry Examples": chapter04.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: roboto
    code: roboto mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
use_directory_urls: false
