site_name: wolfBoot Manual
site_url: https://wolfssl.com/
docs_dir: build/html/
site_dir: html/
copyright: wolfSSL Inc. 2021
nav:
    - "1. Introduction": index.md
    - "2. Compiling wolfBoot": chapter02.md
    - "3. Targets": chapter03.md
    - "4. Hardware Abstraction Layer": chapter04.md
    - "5. Flash Partitions": chapter05.md
    - "6. wolfBoot Features": chapter06.md
    - "7. Integrating wolfBoot in an existing project": chapter07.md
    - "8. Troubleshooting": chapter08.md
theme:
  name: null
  custom_dir: ../mkdocs-material/material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon: "logo.png"
  logo: logo.png
  favicon: logo.png
  feature:
    tabs: true
extra_css: [skin.css]
extra:
    generator: false
use_directory_urls: false
